### ISSUE TITLE
Sync github and npmjs repo

### ISSUE THREAD

**Issue by dominicpaul1911** [textileio/js-textile-wallet#21]
Hey, Looks like the code in github and npmjs are out of sync. Since most the users would npm install, they would be refering to the older version of this package. Kindly please publish the latest to npmjs

**Comment by carsonfarmer** [comment]
Hi @dominicpaul1911, please make sure you're using `@textile/wallet` _not_ `@textile/js-wallet`: https://www.npmjs.com/package/@textile/wallet
